# Generated by Django 6.0.7 on 2026-07-12 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_venta_ventaitem_venta_products_ve_fecha_54c8bb_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='venta',
            name='products_ve_estado_286204_idx',
        ),
        migrations.AddField(
            model_name='producto',
            name='whatsapp_link',
            field=models.URLField(blank=True, help_text='Enlace directo de WhatsApp para este producto', max_length=500),
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente_nombre',
            field=models.CharField(blank=True, help_text='Nombre del cliente', max_length=200),
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente_telefono',
            field=models.CharField(blank=True, help_text='Teléfono del cliente', max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Observaciones del pedido'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Administrador que registró la venta', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='venta',
            name='estado',
        ),
    ]
