# Generated by Django 6.0.7 on 2026-07-19 12:04

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_venta_products_ve_estado_286204_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen del producto (formatos: JPG, PNG, WebP)', null=True, upload_to=products.models.producto_imagen_path),
        ),
    ]
